### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mlucchini**
Removed typos and made instructions slightly more clear.

### CODE REVIEW

**Review by Atry — APPROVED** [review]
LGTM

**Comment by Atry** [comment]
@mlucchini , thank you. I will merge it.

By the way, this repository is the old tutorial for DeepLearning.scala 1.0.

**Comment by mlucchini** [comment]
These are the new ones then? https://github.com/ThoughtWorksInc/DeepLearning.scala-website/tree/master/demo
Should this repository be deleted?

**Comment by Atry** [comment]
This repository is a sbt project for DeepLearning.scala 1.0 (and some old milestone version of 2.0). 

[Those](https://github.com/ThoughtWorksInc/DeepLearning.scala-website/tree/master/demo) are Jupyter Notebooks for 2.0.0.

**Pull request merged**
